### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/myst-nb.example-project#1]
Curren issue with example

```
# Sphinx version: 2.4.0
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   Running Sphinx v2.4.0
#   making output directory...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 2 source files that are out of date
#   updating environment:
#   [new config]
#   2 added, 0 changed, 0 removed
#   reading sources... [ 50%] ar1_processes-MyST
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.0) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/alabaster/__init__.py
#   myst_parser (0.2.0) from /Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/__init__.py
#   myst_nb (0.1.0) from /Users/matthewmckay/repos-collab/lecture-source-py/src/sphinx-notebook/myst_nb/__init__.py
#   sphinxcontrib.bibtex (unknown version) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinxcontrib_bibtex-1.0.0-py3.7.egg/sphinxcontrib/bibtex/__init__.py
#   pandas_sphinx_theme (unknown version) from /Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/pandas_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/sphinx-notebook/myst_nb/parser.py", line 55, in parse
    myst_ast = tokenize(cell["source"].splitlines(keepends=True))
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_token.py", line 59, in tokenize
    return tokenizer.tokenize(lines, _token_types.value, start_line)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_tokenizer.py", line 56, in tokenize
    return make_tokens(tokenize_block(iterable, token_types, start_line))
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_tokenizer.py", line 93, in make_tokens
    token = token_type(result)
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/block_tokens.py", line 514, in __init__
    self.children = [ListItem(*match) for match in matches]
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/block_tokens.py", line 514, in <listcomp>
    self.children = [ListItem(*match) for match in matches]
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_token.py", line 537, in __init__
    self.children = tokenizer.make_tokens(parse_buffer)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_tokenizer.py", line 93, in make_tokens
    token = token_type(result)
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/block_tokens.py", line 332, in __init__
    block_token.BlockToken.__init__(self, content, span_token.tokenize_inner)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/block_token.py", line 134, in __init__
    self.children = tokenize_func(lines)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/span_token.py", line 42, in tokenize_inner
    return tokenizer.tokenize(content, _token_types.value)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/span_tokenizer.py", line 8, in tokenize
    tokens = find_tokens(string, token_types, fallback_token)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/span_tokenizer.py", line 21, in find_tokens
    for m in token_type.find(string):
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/span_tokens.py", line 49, in find
    return find_core_tokens(string, span_token._root_node)
  File "/Users/matthewmckay/repos-collab/lecture-source-py/src/myst-parser/myst_parser/span_tokens.py", line 170, in find_core_tokens
    i = core_tokens.find_link_image(string, i, delimiters, matches, root)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/core_tokens.py", line 134, in find_link_image
    match = match_link_image(string, offset, delimiter, root)
  File "/Users/matthewmckay/anaconda3/envs/myst/lib/python3.7/site-packages/mistletoe/core_tokens.py", line 262, in match_link_image
    dest, title = ref
TypeError: cannot unpack non-iterable bool object
```

**Comment by mmcky** [comment]
@choldgraf any ideas here? The repo just consists of `index` and a single lecture file in `ipynb` format that mirrors the `myst` syntax contained in `md` files.

**Comment by choldgraf** [comment]
hmmm - well it definitely looks like it's choking on the ipynb file. We really need to improve the error reporting in `myst-nb` to report back which cell resulted in errors. I think it'll be hard to debug without figuring out which markup it is messing up on.

Maybe one way to do this is to try replicating this line yourself:

```
myst_ast = tokenize(cell["source"].splitlines(keepends=True))
```

That's just calling the myst_parser "tokenize" function on the cell's contents, which should be easy to loop through your cells and try it on your source content

(about to go to bed, apologies if I drop off!)

**Comment by mmcky** [comment]
ah thanks @choldgraf that is a good idea. I will try that tomorrow.

**Comment by chrisjsewell** [comment]
Yep, first and foremost, its because you don't know how to write Markdown 😜 

In the notebook you have:

[beta distribution](https://en.wikipedia.org/wiki/Beta\_distribution\)

As you can see this does not work, because the last backslash is interpreted as escaping the `)`

You need to remove that:

[beta distribution](https://en.wikipedia.org/wiki/Beta\_distribution)

**Comment by chrisjsewell** [comment]
@choldgraf the reason it is failing in such a 'poor' way though is partly because as noted in
ExecutableBookProject/MyST-Parser#101, you are using `tokenize` instead of `Document`. We said to do that before, so as not to parse front-matter. But actually it also means some global state is not initialized (leading to the error above). I've enow added: [Document(string, inc_front_matter=False)](https://github.com/ExecutableBookProject/MyST-Parser/blob/9d27deeda9bd3418bfabcf064f1a9b4a066f6912/myst_parser/block_tokens.py#L76), so you should be able to use this.

**Comment by chrisjsewell** [comment]
Lastly there is a bug in mistletoe that I should fix here: https://github.com/ExecutableBookProject/mistletoe/blob/2cfe7446b975685f98837f9e40aaabcc0e270a79/mistletoe/core_tokens.py#L301 (I think it should return False or raise an error?)

**Comment by choldgraf** [comment]
@chrisjsewell nice, OK I'll rewrite with document instead of tokenize and see how it catches errors

**Comment by mmcky** [comment]
thanks @chrisjsewell and @choldgraf. This is now working with the latest `master` branches
